// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package main

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/renanbastos93/weaverdemo/ImageScaler",
		Iface: reflect.TypeOf((*ImageScaler)(nil)).Elem(),
		Impl:  reflect.TypeOf(scaler{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return imageScaler_local_stub{impl: impl.(ImageScaler), tracer: tracer, scaleMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/ImageScaler", Method: "Scale", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return imageScaler_client_stub{stub: stub, scaleMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/ImageScaler", Method: "Scale", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return imageScaler_server_stub{impl: impl.(ImageScaler), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return imageScaler_reflect_stub{caller: caller}
		},
		RefData: "⟦553dfbbd:wEaVeReDgE:github.com/renanbastos93/weaverdemo/ImageScaler→github.com/renanbastos93/weaverdemo/LocalCache⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "github.com/renanbastos93/weaverdemo/LocalCache",
		Iface: reflect.TypeOf((*LocalCache)(nil)).Elem(),
		Impl:  reflect.TypeOf(implLocalCache{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return localCache_local_stub{impl: impl.(LocalCache), tracer: tracer, getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/LocalCache", Method: "Get", Remote: false, Generated: true}), setMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/LocalCache", Method: "Set", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return localCache_client_stub{stub: stub, getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/LocalCache", Method: "Get", Remote: true, Generated: true}), setMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/renanbastos93/weaverdemo/LocalCache", Method: "Set", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return localCache_server_stub{impl: impl.(LocalCache), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return localCache_reflect_stub{caller: caller}
		},
		RefData: "⟦4070fd4e:wEaVeReDgE:github.com/renanbastos93/weaverdemo/LocalCache→github.com/renanbastos93/weaverdemo/ImageScaler⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/weaver/Main",
		Iface: reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:  reflect.TypeOf(implBFF{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦50668105:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→github.com/renanbastos93/weaverdemo/ImageScaler⟧\n",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[ImageScaler] = (*scaler)(nil)
var _ weaver.InstanceOf[LocalCache] = (*implLocalCache)(nil)
var _ weaver.InstanceOf[weaver.Main] = (*implBFF)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*scaler)(nil)
var _ weaver.Unrouted = (*implLocalCache)(nil)
var _ weaver.Unrouted = (*implBFF)(nil)

// Local stub implementations.

type imageScaler_local_stub struct {
	impl         ImageScaler
	tracer       trace.Tracer
	scaleMetrics *codegen.MethodMetrics
}

// Check that imageScaler_local_stub implements the ImageScaler interface.
var _ ImageScaler = (*imageScaler_local_stub)(nil)

func (s imageScaler_local_stub) Scale(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.scaleMetrics.Begin()
	defer func() { s.scaleMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.ImageScaler.Scale", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Scale(ctx, a0)
}

type localCache_local_stub struct {
	impl       LocalCache
	tracer     trace.Tracer
	getMetrics *codegen.MethodMetrics
	setMetrics *codegen.MethodMetrics
}

// Check that localCache_local_stub implements the LocalCache interface.
var _ LocalCache = (*localCache_local_stub)(nil)

func (s localCache_local_stub) Get(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.LocalCache.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0)
}

func (s localCache_local_stub) Set(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	begin := s.setMetrics.Begin()
	defer func() { s.setMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.LocalCache.Set", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Set(ctx, a0, a1)
}

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

// Client stub implementations.

type imageScaler_client_stub struct {
	stub         codegen.Stub
	scaleMetrics *codegen.MethodMetrics
}

// Check that imageScaler_client_stub implements the ImageScaler interface.
var _ ImageScaler = (*imageScaler_client_stub)(nil)

func (s imageScaler_client_stub) Scale(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.scaleMetrics.Begin()
	defer func() { s.scaleMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.ImageScaler.Scale", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

type localCache_client_stub struct {
	stub       codegen.Stub
	getMetrics *codegen.MethodMetrics
	setMetrics *codegen.MethodMetrics
}

// Check that localCache_client_stub implements the LocalCache interface.
var _ LocalCache = (*localCache_client_stub)(nil)

func (s localCache_client_stub) Get(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.LocalCache.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

func (s localCache_client_stub) Set(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.setMetrics.Begin()
	defer func() { s.setMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.LocalCache.Set", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.2 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type imageScaler_server_stub struct {
	impl    ImageScaler
	addLoad func(key uint64, load float64)
}

// Check that imageScaler_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*imageScaler_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s imageScaler_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Scale":
		return s.scale
	default:
		return nil
	}
}

func (s imageScaler_server_stub) scale(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Scale(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type localCache_server_stub struct {
	impl    LocalCache
	addLoad func(key uint64, load float64)
}

// Check that localCache_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*localCache_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s localCache_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Get":
		return s.get
	case "Set":
		return s.set
	default:
		return nil
	}
}

func (s localCache_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s localCache_server_stub) set(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Set(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

// Reflect stub implementations.

type imageScaler_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that imageScaler_reflect_stub implements the ImageScaler interface.
var _ ImageScaler = (*imageScaler_reflect_stub)(nil)

func (s imageScaler_reflect_stub) Scale(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("Scale", ctx, []any{a0}, []any{&r0})
	return
}

type localCache_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that localCache_reflect_stub implements the LocalCache interface.
var _ LocalCache = (*localCache_reflect_stub)(nil)

func (s localCache_reflect_stub) Get(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("Get", ctx, []any{a0}, []any{&r0})
	return
}

func (s localCache_reflect_stub) Set(ctx context.Context, a0 string, a1 string) (err error) {
	err = s.caller("Set", ctx, []any{a0, a1}, []any{})
	return
}

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

